kind: pipeline
type: docker
name: default
steps:
    - name: deploy-demo
      image: appleboy/drone-ssh
      environment:
          ENV_VARS:
              from_secret: env_vars
      settings:
          host: 45.125.34.94
          username: pincman
          key:
              from_secret: ssh_key
          port: 22
          envs: [ENV_VARS]
          script:
              - 'mkdir -p /home/pincman/htdocs/kuromi && cd $_'
              - '[ -d ./api ] && rm -rf ./api'
              - GIT_SSH_COMMAND="ssh -o StrictHostKeyChecking=no" git clone -q git@git.3rcd.com:kuromi/api.git ./api
              - cd api && echo "$${ENV_VARS}" > .env
              - 'source ~/.zshrc; pnpm i && pnpm build && node ./dist/main.js dbmg -s &&  pm2 restart ecosystem.config.js && pm2 save'
